### ISSUE TITLE
Upgrade to React v0.14

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1332] opened 2015-10-13 17:48 UTC
for details see https://facebook.github.io/react/blog/

**Comment by hannahkane** [comment] 2015-12-21 18:28
Is this a dupe of the work @Pomax is doing? Should we close?

**Comment by Pomax** [comment] 2015-12-21 18:41
very much, already addressed in #1460

**Closed by Pomax** 2015-12-21 18:41 UTC
Labels: dev
