### ISSUE TITLE
Use sure we use MoFo JS Style Guide

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1568] opened 2016-01-25 20:52 UTC
Once the new build system is it, we should make sure we are using the Mozilla Foundation JS Style Guide: https://github.com/MozillaFoundation/javascript-style-guide

**Comment by Pomax** [comment] 2016-01-25 20:53
duplicate of https://github.com/mozilla/teach.mozilla.org/issues/1557

**Closed by Pomax** 2016-01-25 20:53 UTC
Labels: blocked, dev
